package env

type RegionConfig struct {
	Code         string
	Name         string
	LangPrefixes []string
	TimeZones    []string
	UTCOffsets   []int
	CountryCodes []string
	Priority     int
}

var regionConfigs = []RegionConfig{
	{
		Code:         "cn",
		Name:         "China",
		LangPrefixes: []string{"zh"},
		TimeZones:    []string{"Asia/Shanghai", "Asia/Chongqing", "Asia/Harbin", "Asia/Beijing", "PRC", "CST"},
		UTCOffsets:   []int{8 * 60 * 60},
		CountryCodes: []string{"CN"},
		Priority:     1,
	},
	{
		Code:         "us",
		Name:         "United States",
		LangPrefixes: []string{"en"},
		TimeZones:    []string{"America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles", "America/Phoenix", "US/Eastern", "US/Central", "US/Mountain", "US/Pacific"},
		UTCOffsets:   []int{-5 * 60 * 60, -6 * 60 * 60, -7 * 60 * 60, -8 * 60 * 60},
		CountryCodes: []string{"US"},
		Priority:     2,
	},
	{
		Code:         "eu",
		Name:         "Europe",
		LangPrefixes: []string{"en", "de", "fr", "es", "it", "pt", "nl", "sv", "no", "da", "fi", "pl", "cs", "sk", "hu", "ro", "bg", "hr", "sl", "et", "lv", "lt", "el", "mt", "ga", "cy"},
		TimeZones:    []string{"Europe/London", "Europe/Paris", "Europe/Berlin", "Europe/Rome", "Europe/Madrid", "Europe/Amsterdam", "Europe/Stockholm", "Europe/Oslo", "Europe/Copenhagen", "Europe/Helsinki", "Europe/Warsaw", "Europe/Prague", "Europe/Budapest", "Europe/Bucharest", "Europe/Sofia", "Europe/Athens", "Europe/Vienna", "Europe/Brussels", "Europe/Dublin"},
		UTCOffsets:   []int{0, 1 * 60 * 60, 2 * 60 * 60},
		CountryCodes: []string{"GB", "DE", "FR", "ES", "IT", "PT", "NL", "SE", "NO", "DK", "FI", "PL", "CZ", "SK", "HU", "RO", "BG", "HR", "SI", "EE", "LV", "LT", "GR", "MT", "IE", "AT", "BE"},
		Priority:     3,
	},
	{
		Code:         "jp",
		Name:         "Japan",
		LangPrefixes: []string{"ja"},
		TimeZones:    []string{"Asia/Tokyo", "Japan", "JST"},
		UTCOffsets:   []int{9 * 60 * 60},
		CountryCodes: []string{"JP"},
		Priority:     4,
	},
	{
		Code:         "kr",
		Name:         "South Korea",
		LangPrefixes: []string{"ko"},
		TimeZones:    []string{"Asia/Seoul", "Korea", "KST"},
		UTCOffsets:   []int{9 * 60 * 60},
		CountryCodes: []string{"KR"},
		Priority:     5,
	},
	{
		Code:         "in",
		Name:         "India",
		LangPrefixes: []string{"hi", "en"},
		TimeZones:    []string{"Asia/Kolkata", "Asia/Calcutta", "India", "IST"},
		UTCOffsets:   []int{5*60*60 + 30*60},
		CountryCodes: []string{"IN"},
		Priority:     6,
	},
	{
		Code:         "sg",
		Name:         "Singapore",
		LangPrefixes: []string{"en"},
		TimeZones:    []string{"Asia/Singapore", "Singapore", "SGT"},
		UTCOffsets:   []int{8 * 60 * 60},
		CountryCodes: []string{"SG"},
		Priority:     7,
	},
	{
		Code:         "au",
		Name:         "Australia",
		LangPrefixes: []string{"en"},
		TimeZones:    []string{"Australia/Sydney", "Australia/Melbourne", "Australia/Perth", "Australia/Brisbane", "Australia/Adelaide", "Australia/Darwin", "Australia/Canberra", "Australia/Hobart"},
		UTCOffsets:   []int{8 * 60 * 60, 9 * 60 * 60, 9*60*60 + 30*60, 10 * 60 * 60},
		CountryCodes: []string{"AU"},
		Priority:     8,
	},
	{
		Code:         "br",
		Name:         "Brazil",
		LangPrefixes: []string{"pt"},
		TimeZones:    []string{"America/Sao_Paulo", "America/Rio_de_Janeiro", "America/Bahia", "America/Belem", "America/Recife", "America/Fortaleza", "America/Manaus", "America/Cuiaba", "America/Porto_Velho", "America/Boa_Vista", "America/Eirunepe", "America/Rio_Branco", "Brazil"},
		UTCOffsets:   []int{-5 * 60 * 60, -4 * 60 * 60, -3 * 60 * 60, -2 * 60 * 60},
		CountryCodes: []string{"BR"},
		Priority:     9,
	},
	{
		Code:         "ru",
		Name:         "Russia",
		LangPrefixes: []string{"ru"},
		TimeZones:    []string{"Europe/Moscow", "Europe/Samara", "Europe/Ulyanovsk", "Europe/Astrakhan", "Europe/Saratov", "Asia/Yekaterinburg", "Asia/Omsk", "Asia/Novosibirsk", "Asia/Barnaul", "Asia/Novokuznetsk", "Asia/Krasnoyarsk", "Asia/Irkutsk", "Asia/Chita", "Asia/Yakutsk", "Asia/Khandyga", "Asia/Vladivostok", "Asia/Ust-Nera", "Asia/Magadan", "Asia/Sakhalin", "Asia/Srednekolymsk", "Asia/Kamchatka", "Asia/Anadyr"},
		UTCOffsets:   []int{2 * 60 * 60, 3 * 60 * 60, 4 * 60 * 60, 5 * 60 * 60, 6 * 60 * 60, 7 * 60 * 60, 8 * 60 * 60, 9 * 60 * 60, 10 * 60 * 60, 11 * 60 * 60, 12 * 60 * 60},
		CountryCodes: []string{"RU"},
		Priority:     10,
	},
	{
		Code:         "ca",
		Name:         "Canada",
		LangPrefixes: []string{"en", "fr"},
		TimeZones:    []string{"America/Toronto", "America/Vancouver", "America/Montreal", "America/Edmonton", "America/Winnipeg", "America/Halifax", "America/Regina", "America/St_Johns", "America/Whitehorse", "America/Dawson", "America/Inuvik", "America/Iqaluit", "Canada/Central", "Canada/Eastern", "Canada/Mountain", "Canada/Pacific"},
		UTCOffsets:   []int{-8 * 60 * 60, -7 * 60 * 60, -6 * 60 * 60, -5 * 60 * 60, -4 * 60 * 60, -3*60*60 - 30*60},
		CountryCodes: []string{"CA"},
		Priority:     11,
	},
	{
		Code:         "mx",
		Name:         "Mexico",
		LangPrefixes: []string{"es"},
		TimeZones:    []string{"America/Mexico_City", "America/Tijuana", "America/Mazatlan", "America/Chihuahua", "America/Monterrey", "America/Merida", "America/Cancun", "America/Hermosillo", "America/Matamoros"},
		UTCOffsets:   []int{-8 * 60 * 60, -7 * 60 * 60, -6 * 60 * 60, -5 * 60 * 60},
		CountryCodes: []string{"MX"},
		Priority:     12,
	},
	{
		Code:         "za",
		Name:         "South Africa",
		LangPrefixes: []string{"en", "af", "zu", "xh"},
		TimeZones:    []string{"Africa/Johannesburg", "Africa/Cape_Town", "Africa/Durban", "Africa/Maseru", "Africa/Mbabane"},
		UTCOffsets:   []int{2 * 60 * 60},
		CountryCodes: []string{"ZA"},
		Priority:     13,
	},
	{
		Code:         "eg",
		Name:         "Egypt",
		LangPrefixes: []string{"ar"},
		TimeZones:    []string{"Africa/Cairo", "Egypt"},
		UTCOffsets:   []int{2 * 60 * 60},
		CountryCodes: []string{"EG"},
		Priority:     14,
	},
	{
		Code:         "ar",
		Name:         "Argentina",
		LangPrefixes: []string{"es"},
		TimeZones:    []string{"America/Argentina/Buenos_Aires", "America/Argentina/Cordoba", "America/Argentina/Jujuy", "America/Argentina/Tucuman", "America/Argentina/Catamarca", "America/Argentina/La_Rioja", "America/Argentina/San_Juan", "America/Argentina/Mendoza", "America/Argentina/San_Luis", "America/Argentina/Rio_Gallegos", "America/Argentina/Ushuaia"},
		UTCOffsets:   []int{-3 * 60 * 60},
		CountryCodes: []string{"AR"},
		Priority:     15,
	},
	{
		Code:         "sa",
		Name:         "Saudi Arabia",
		LangPrefixes: []string{"ar"},
		TimeZones:    []string{"Asia/Riyadh", "Asia/Mecca", "Asia/Medina", "Asia/Dammam"},
		UTCOffsets:   []int{3 * 60 * 60},
		CountryCodes: []string{"SA"},
		Priority:     16,
	},
	{
		Code:         "th",
		Name:         "Thailand",
		LangPrefixes: []string{"th"},
		TimeZones:    []string{"Asia/Bangkok", "Asia/Phuket", "Asia/Chiang_Mai"},
		UTCOffsets:   []int{7 * 60 * 60},
		CountryCodes: []string{"TH"},
		Priority:     17,
	},
	{
		Code:         "id",
		Name:         "Indonesia",
		LangPrefixes: []string{"id"},
		TimeZones:    []string{"Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura"},
		UTCOffsets:   []int{7 * 60 * 60, 8 * 60 * 60, 9 * 60 * 60},
		CountryCodes: []string{"ID"},
		Priority:     18,
	},
	{
		Code:         "my",
		Name:         "Malaysia",
		LangPrefixes: []string{"ms", "en"},
		TimeZones:    []string{"Asia/Kuala_Lumpur", "Asia/Kuching"},
		UTCOffsets:   []int{8 * 60 * 60},
		CountryCodes: []string{"MY"},
		Priority:     19,
	},
	{
		Code:         "ph",
		Name:         "Philippines",
		LangPrefixes: []string{"en", "tl"},
		TimeZones:    []string{"Asia/Manila"},
		UTCOffsets:   []int{8 * 60 * 60},
		CountryCodes: []string{"PH"},
		Priority:     20,
	},
	{
		Code:         "vn",
		Name:         "Vietnam",
		LangPrefixes: []string{"vi"},
		TimeZones:    []string{"Asia/Ho_Chi_Minh", "Asia/Saigon"},
		UTCOffsets:   []int{7 * 60 * 60},
		CountryCodes: []string{"VN"},
		Priority:     21,
	},
	{
		Code:         "tr",
		Name:         "Turkey",
		LangPrefixes: []string{"tr"},
		TimeZones:    []string{"Europe/Istanbul", "Asia/Istanbul", "Turkey"},
		UTCOffsets:   []int{3 * 60 * 60},
		CountryCodes: []string{"TR"},
		Priority:     22,
	},
	{
		Code:         "il",
		Name:         "Israel",
		LangPrefixes: []string{"he", "ar", "en"},
		TimeZones:    []string{"Asia/Jerusalem", "Asia/Tel_Aviv", "Israel"},
		UTCOffsets:   []int{2 * 60 * 60},
		CountryCodes: []string{"IL"},
		Priority:     23,
	},
	{
		Code:         "uae",
		Name:         "United Arab Emirates",
		LangPrefixes: []string{"ar"},
		TimeZones:    []string{"Asia/Dubai", "Asia/Abu_Dhabi", "Asia/Sharjah"},
		UTCOffsets:   []int{4 * 60 * 60},
		CountryCodes: []string{"AE"},
		Priority:     24,
	},
	{
		Code:         "ng",
		Name:         "Nigeria",
		LangPrefixes: []string{"en", "ha", "yo", "ig"},
		TimeZones:    []string{"Africa/Lagos", "Africa/Abuja"},
		UTCOffsets:   []int{1 * 60 * 60},
		CountryCodes: []string{"NG"},
		Priority:     25,
	},
	{
		Code:         "ke",
		Name:         "Kenya",
		LangPrefixes: []string{"en", "sw"},
		TimeZones:    []string{"Africa/Nairobi"},
		UTCOffsets:   []int{3 * 60 * 60},
		CountryCodes: []string{"KE"},
		Priority:     26,
	},
	{
		Code:         "pk",
		Name:         "Pakistan",
		LangPrefixes: []string{"ur", "en"},
		TimeZones:    []string{"Asia/Karachi", "Asia/Lahore"},
		UTCOffsets:   []int{5 * 60 * 60},
		CountryCodes: []string{"PK"},
		Priority:     27,
	},
	{
		Code:         "bd",
		Name:         "Bangladesh",
		LangPrefixes: []string{"bn", "en"},
		TimeZones:    []string{"Asia/Dhaka"},
		UTCOffsets:   []int{6 * 60 * 60},
		CountryCodes: []string{"BD"},
		Priority:     28,
	},
	{
		Code:         "lk",
		Name:         "Sri Lanka",
		LangPrefixes: []string{"si", "ta", "en"},
		TimeZones:    []string{"Asia/Colombo"},
		UTCOffsets:   []int{5*60*60 + 30*60},
		CountryCodes: []string{"LK"},
		Priority:     29,
	},
	{
		Code:         "np",
		Name:         "Nepal",
		LangPrefixes: []string{"ne", "en"},
		TimeZones:    []string{"Asia/Kathmandu"},
		UTCOffsets:   []int{5*60*60 + 45*60},
		CountryCodes: []string{"NP"},
		Priority:     30,
	},
}

func GetRegionConfig(code string) *RegionConfig {
	for _, config := range regionConfigs {
		if config.Code == code {
			return &config
		}
	}
	return nil
}

func GetAllRegionConfigs() []RegionConfig {
	return regionConfigs
}
